---
name: "Setup node for an action"
description: "Setup node package, cache and path for an action"
inputs:
  actionPath:
    description: "calling action path's to setup"

runs:
  using: "composite"

  steps:
    - name: 'Cache Dependencies'
      uses: 'actions/cache@v3'
      id: cache-node-modules
      with:
        path: 'node_modules'
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      # the shell to be used is required in composite custom actions
      shell: bash